### ISSUE TITLE
How do I get "model.ckpt"?

### ISSUE THREAD

**Issue by capybararara** [tuanct1997/Federated-Learning-ASR-based-on-wav2vec-2.0#2]
--pre_train_model_path="..../material/model.ckpt" \
How do I get "model.ckpt"?

**Comment by tuanct1997** [comment]
Hi, 

For the --pre_train_model_path option, it's default set to None. So if you have your own pre-trained model, you can pass it through that args, if not, you can skip it.  Currently, we don't provide any pre-trained model.

**Comment by capybararara** [comment]
Alright. How long would it take me to train with 4 V100 graphics cards if I didn't use the pre-training model？


> Hi,
> 
> For the --pre_train_model_path option, it's default set to None. So if you have your own pre-trained model, you can pass it through that args, if not, you can skip it. Currently, we don't provide any pre-trained model.

**Comment by tuanct1997** [comment]
> train with 4 V100 graphics cards if I didn't use the pre-training model？

With 4 V100 GPUs, using same dataset that we provided, you can get our performance in the paper after about 3-4 days for 100 rounds. And it's may better if you keep it longer so more speakers can be involved.

**Comment by capybararara** [comment]
By the way, the 'fraction_fit' 's type and default are 'int' and '10', however, the exmple's 'fraction_fit' is '0.01'. Is it supposed to be 'float' or '1'?

**Comment by tuanct1997** [comment]
thank you for noticing. It's a typo error. It should be "type=floa"t, default should be "0.01" since W2v2 model is huge for simulation. 

I will update the code asap. About the pre-trained model, we will provide the checkpoint in near future.

**Comment by capybararara** [comment]
> I will update the code asap. About the pre-trained model, we will provide the checkpoint in near future.

It will help a lot. Thank you.

**Comment by capybararara** [comment]
What versions of python, ray and Ray-Proxy are you using?

**Comment by tuanct1997** [comment]
I'm using python 3.8 but it should work with all python3. For ray, there is no recommend for version from flower so it should be fine with any version. I highly recommend from 1.9 and above

**Comment by tuanct1997** [comment]
The error has been fixed, Checkpoint is provided I will close the issue.

**Comment by capybararara** [comment]
Ok, thank you!
