### ISSUE TITLE
ImportError: cannot import name 'parameters_to_weights' from 'flwr.common'

### ISSUE THREAD

**Issue by sultanoid** [tuanct1997/Federated-Learning-ASR-based-on-wav2vec-2.0#6]
I have installed flwr==1.4.0 to run this repository. But when I am running the following command, I am getting this error, `"ImportError: cannot import name 'parameters_to_weights' from 'flwr.common'"`. How can I solve this error? 

```
python fl_w2v.py \
  --data_path="./data" \
  --config_path="./configs/w2v2.yaml" \
  --min_fit_clients=2 \
  --running_type="cpu" \
  --min_available_clients=2 \
  --output="./output/" \
  --fraction_fit=0.01 \
  --rounds=2 \
  --parallel_backend=True \
  --pre_train_model_path="..../material/model.ckpt" \
  --label_path="/users/tnguyen/Federated_learning/results/mcadam/1234/save/label_encoder.txt" \
  --local_epochs=1
```

**Comment by tuanct1997** [comment]
Hi, 
This error due to flower change variable from 1.0 version and above. I'm working on it with the help of flower team to update the code in near future. Currently, to use this recipe, I suggest using` Flower <=0.18.0, >= 0.17.0`

**Comment by sultanoid** [comment]
Thanks a lot. This solves my issue.
